// MyTest.usf 
#include "/Engine/Public/Platform.ush"
// Simple pass-through vertex shader

void MainVS(float4 InPosition : ATTRIBUTE0, float2 InUV : ATTRIBUTE1, out float2 OutUV : TEXCOORD0, out float4 OutPosition : SV_POSITION)
{
	OutPosition = InPosition;
	OutUV = InUV;

}

// Simple solid color pixel shader
float4 StartColor;
void MainPS(
in float2 uv : TEXCOORD0, out float4 OutColor : SV_Target0
) 
{
	OutColor = StartColor;
}
